Add ability to perform handshake after establishing connection
membraneframework/membrane_ice_plugin pull request #10
Opened 2020-09-28 12:46 UTC by mickel8

2020-10-13 10:35 UTC, mat-hek requested changes

2020-10-13 10:35 UTC, mat-hek commented on lib/membrane_ice/sink.ex
> +    case ExLibnice.add_stream(ice, n_components, stream_name) do
I think this should be done in `handle_stopped_to_prepared`

2020-10-13 10:35 UTC, mat-hek commented on test/membrane_ice/integration_test.exs
> +  @file_path "./ice-recv.h264"
why not tmp?

2020-10-13 10:35 UTC, mat-hek commented on lib/membrane_ice/sink.ex
> +  def handle_init(%__MODULE__{handshake_module: Handshake.Default} = options) do
Special branches for the default handshake should be avoided

2020-10-13 10:35 UTC, mat-hek commented on lib/membrane_ice/sink.ex
> +  defp handle_init(options, handshake_state) do
Giving a private function the same name as a public one is confusing, it's usually solved by adding `do_` prefix, like `do_handle_init`

2020-10-23 09:07 UTC, mat-hek requested changes

2020-10-23 09:07 UTC, mat-hek commented on lib/membrane_ice/handshake/default.ex
> +    {:finished, nil}
if we finish here instead of init, can't it happen that the first chunk of stream lands here and gets ignored?

2020-10-23 09:07 UTC, mat-hek commented on lib/membrane_ice/common.ex
> +# credo:disable-for-this-file Credo.Check.Readability.Specs
I think specs shouldn't be omitted here

2020-10-30 13:27 UTC, mickel8 commented on lib/membrane_ice/handshake/default.ex
> +    {:finished, nil}
Yeah, I missed this

2020-10-30 13:31 UTC, mickel8 commented on lib/membrane_ice/common.ex
> +  defp update_state_and_return(component_id, handshake_ctx, handshake_data, handshakes, state) do
Yeah, the only reason was not to duplicate this code.

2020-10-30 13:58 UTC, mickel8 commented on lib/membrane_ice/handshake/default.ex
> +    {:finished, nil}
EDIT
I think it's okay. Component has to be in READY state to convey payload to the user. When it receives message `component_state_ready` it imidiately finishes handshake. If it received remote payload before changing state to READY  it would discard it anyway even if we marked handshake as finished in `init` function. It would also be a llitle strange to end handshake even before invoking `connection_ready` function.

2020-10-30 13:59 UTC, mickel8 commented on lib/membrane_ice/common.ex
> +      end
There are some slight differences e.g. checking set with connections that make it very hard to make this code common

2020-10-30 15:29 UTC, mat-hek commented on lib/membrane_ice/handshake/default.ex
> +    {:finished, nil}
> Component has to be in READY state to convey payload to the user

I don't quite get why we can conduct handshake before the ready state but not convey payloads? How does it differ from the ICE perspective?

2020-10-30 15:33 UTC, mickel8 commented on lib/membrane_ice/common.ex
> +# credo:disable-for-this-file Credo.Check.Readability.Specs
Hmm, I didn't include them because in fact module `common` consists only of `handle_ice_message` which is acctually `handle_info` and we don't (afaik) write specs for callbacks from `membrane_core`. I can write them but not sure If someone will use them?

Also messages returned from `handle_ice_message` are `membrane` actions so imo this wouldn't be too readable.

2020-10-30 15:35 UTC, mat-hek commented on lib/membrane_ice/common.ex
> +      end
Checking the set with connections seems outside the lines I marked... From what I see, the code is exactly the same apart from the raw `:ok` clause and not delegating work to `update_state_and_return`

2020-10-30 15:39 UTC, mat-hek commented on lib/membrane_ice/common.ex
> +# credo:disable-for-this-file Credo.Check.Readability.Specs
The specs are useful also for future us and dialyzer. You don't need to narrow them down too much, `Membrane.Element.Action.t` is enough even if you don't use all the actions from there

2020-10-30 15:45 UTC, mat-hek commented on lib/membrane_ice/common.ex
> +      end
Ok, I see it changed in the last commit, but I still think you can make it common. For example, you can try to create a function that conditionally executes given callback, updates state and returns something like `{finished?, packets, state}`

2020-10-31 17:27 UTC, mickel8 commented on lib/membrane_ice/handshake/default.ex
> +    {:finished, nil}
Nope, we can't. So let's allow reading messages earlier i.e in the CONNECTED state but sending only when in the READY state. In this approach I will also finish default handshake in init function as you wrote so we don't lose any packets.

2020-11-06 12:34 UTC, mickel8 commented on lib/membrane_ice/handshake/default.ex
> +    {:finished, nil}
Now we finish in init but to allow receiving messages before READY state I have to change more code so I will do this in next PR in which I will also remove dynamic pads and move starting ICE to `handle_prepared_to_playing`

2020-11-06 13:32 UTC, mat-hek commented on lib/membrane_ice/common.ex
> +  @spec handle_ice_message(:get_local_credentials, ctx :: PlaybackChange.t(), state :: State.t()) ::
In this case, it's better to have a single spec for all clauses
```
@spec handle_ice_message(:get_local_credentials | :set_remote_credentials | ..., ctx :: PlaybackChange.t(), state :: State.t()) :: Base.callback_return_t()
```

2020-11-06 13:32 UTC, mat-hek commented on lib/membrane_ice/handshake/handshake.ex
> +  @type ctx :: term()
it's usually called state ;)

2020-11-06 13:42 UTC, mickel8 commented on lib/membrane_ice/handshake/handshake.ex
> +  @type ctx :: term()
Yeah but there is already `handshake_state` which can be `:in_progress | :finished`

2020-11-06 15:05 UTC, mat-hek commented on lib/membrane_ice/handshake/handshake.ex
> +  @type ctx :: term()
`handshake_state` could become `handshake_status`

2020-11-06 18:07 UTC, mat-hek approved these changes

2020-11-06 18:08 UTC, merged