Improve pads linking
membraneframework/membrane_ice_plugin pull request #12
Opened 2020-11-06 15:47 UTC by mickel8

Allow receiving messages before changing state to READY. Force pads linking before changing state to `playing`

2020-11-09 09:27 UTC, mat-hek requested changes

2020-11-09 09:27 UTC, mat-hek commented on examples/example_project/README.md
> +you have to wait for all of them, link all of them and then play pipeline.
Not sure why is the linking of pads needed after `component_state_ready`. I think it would be easier to have them linked in stopped like in case of the source. Concerning switching to `playing`, there are two better options here:
- use https://hexdocs.pm/membrane_core/Membrane.Element.Action.html#t:playback_change_t/0 to wait till ICE gets connected
- just don't issue demands until ICE gets connected

2020-11-12 18:46 UTC, mat-hek requested changes

2020-11-12 19:28 UTC, mickel8 commented on lib/membrane_ice/source.ex
> +            Pad for component: #{component_id} not added yet. Ignoring payload.
Yeah, I missed that I pattern match against `playback_state: :playing` here but why should I move `handle_stopped_to_prepared` to `handle_prepared_to_playing`?  I mean I can but I thought that we want initialize internal state in stopped, don't we?

2020-11-13 07:36 UTC, mat-hek commented on lib/membrane_ice/source.ex
> +            Pad for component: #{component_id} not added yet. Ignoring payload.
Because this way packets may still come in prepared

2020-11-13 17:04 UTC, mat-hek commented on lib/membrane_ice/sink.ex
> +    if playback_state == :playing do
it's always playing

2020-11-26 12:26 UTC, mat-hek commented on lib/membrane_ice_plugin/common.ex
> +    []
this shouldn't happen, should it?

2020-11-26 12:31 UTC, mickel8 commented on lib/membrane_ice_plugin/common.ex
> +    []
Sink indeed shouldn't receive any data but I am not sure if we can guarantee that the other side doesn't send something to us. In this case we will ignore this but I can remove it too.

2020-11-26 12:33 UTC, mat-hek commented on lib/membrane_ice_plugin/common.ex
> +    []
ok, please warn about that

2020-11-26 12:39 UTC, mat-hek approved these changes

2020-11-26 12:42 UTC, merged