Make Sink and Source work on common connection
membraneframework/membrane_ice_plugin pull request #13
Opened 2020-11-30 09:59 UTC by mickel8

From now ICE Sink and Source use the same connection for sending and receiving messages. 
To provide this functionality ICE Bin has been introduced.

2020-12-18 12:02 UTC, mat-hek requested changes

2020-12-18 12:02 UTC, mat-hek commented on lib/membrane_ice_plugin/source.ex
> +        []
can it happen?

2020-12-18 12:02 UTC, mat-hek commented on lib/membrane_ice_plugin/sink.ex
> +      {:ok, state}
can it happen?

2020-12-18 12:02 UTC, mat-hek commented on lib/membrane_ice_plugin/ice_bin.ex
> +  want to miss any messages do it before playing your pipeline.
I think this will result in an error now

2020-12-18 12:16 UTC, mickel8 commented on lib/membrane_ice_plugin/sink.ex
> +      {:ok, state}
This should happen in most cases. The intention is as follows: when you link after playing pipeline there is a high probability that component is ready so we send demands and event (the first branch of `if`). When you link before playing pipeline you will receive event and demands as soon as connection is established i.e from `handle_other({:component_ready...})` so we do nothing (2nd branch of `if`).

2020-12-18 12:19 UTC, mickel8 commented on lib/membrane_ice_plugin/source.ex
> +        []
Yeap, this should work in a similar way as Sink works. We can link source after establishing connection - after playing pipeline. In this case we will send event in `handle_pad_added`

2020-12-18 12:23 UTC, mickel8 commented on lib/membrane_ice_plugin/ice_bin.ex
> +  same ICE connection.
Actually our `echo_demo` need this. Should we implement it now or leave it as it is and make issue for this? Implementing it now should probably be better as it will affect API

2020-12-18 12:30 UTC, mat-hek commented on lib/membrane_ice_plugin/ice_bin.ex
> +  same ICE connection.
I think we're going to need the funnel shortly anyway, so maybe let's implement it now

2020-12-21 13:29 UTC, mat-hek commented on lib/membrane_ice_plugin/source.ex
> +    state = Bunch.Struct.put_in(state, [:components_handshake_data, component_id], handshake_data)
since the state is not a struct, let's use `Kernel.put_in`

2020-12-21 13:29 UTC, mat-hek commented on lib/membrane_ice_plugin/ice_bin.ex
> +      {:ok, state}
I'd warn here

2020-12-21 15:21 UTC, mat-hek approved these changes

2020-12-21 16:53 UTC, merged