maintenance
membraneframework/membrane_ice_plugin pull request #19
Opened 2022-09-02 12:03 UTC by mat-hek

2022-09-02 12:10 UTC, FelonEkonom approved these changes

2022-09-02 13:11 UTC, Janix4000 requested changes
Split this single `maintenance`  commit into two and create a commit describing the logic change in the 'ice_endpoint.ex`.

2022-09-02 13:11 UTC, Janix4000 commented on lib/membrane_ice_plugin/ice_endpoint.ex
> +    %{
Is it intentional?

2022-09-06 15:13 UTC, Janix4000 approved these changes
Approve

2022-09-06 15:33 UTC, merged