Dtls alerts
membraneframework/membrane_ice_plugin pull request #21
Opened 2021-03-04 14:45 UTC by mickel8

2021-03-16 08:59 UTC, mat-hek requested changes

2021-03-16 08:59 UTC, mat-hek commented on lib/membrane_ice_plugin/handshake/handshake.ex
> +              | {:error, value :: integer()}
We're ignoring these errors for now, but is there any way we can handle them in the future?  Why is the value integer?

2021-03-16 08:59 UTC, mat-hek commented on lib/membrane_ice_plugin/handshake/handshake.ex
> +              | {:hsk_packets, packets :: binary()}
I can understand abbreviating handshake to hsk in private variables, though I'd definitely avoid that in public API. Though that may be confusing to have handshake in some places and hsk in others.
P.s. please do such refactor in separate commits if possible ;)

2021-03-16 08:59 UTC, mat-hek commented on lib/membrane_ice_plugin/sink.ex
> +      {{:ok, actions}, state}
that's great, looks much better now ;)

2021-03-16 11:17 UTC, mickel8 commented on lib/membrane_ice_plugin/handshake/handshake.ex
> +              | {:error, value :: integer()}
I have changed it in ex_dtls so it returns `{:error, :peer_closed_for_writing}` at this moment. It's a good question how to handle such error. Should we stop ICE Bin or send this message to pipeline?

2021-03-16 11:25 UTC, mat-hek commented on lib/membrane_ice_plugin/handshake/handshake.ex
> +              | {:error, value :: integer()}
I think in such cases we should raise ASAP. If one day we know how to handle that, we'll update the API

2021-03-16 12:21 UTC, mickel8 commented on lib/membrane_ice_plugin/handshake/handshake.ex
> +              | {:error, value :: integer()}
I am thinking about videroom. If we raise here our videoroom will fail so at the end we will still raise when DTLS alert occurs but with different message. Maybe let's convey this error up to the parent as `{:connection_closed, cause}`. In such scenario WebRTC plugin or videoroom can stop themselves.

2021-03-17 10:50 UTC, mat-hek commented on lib/membrane_ice_plugin/handshake/handshake.ex
> +              | {:error, value :: integer()}
connection_closed shouldn't be returned as an error, it's rather a normal situation

2021-03-18 10:32 UTC, mickel8 commented on lib/membrane_ice_plugin/handshake/handshake.ex
> +              | {:error, value :: integer()}
True that, now we distinguish between error and closing connection. When error occurs we stop gen server.

2021-03-18 12:29 UTC, mat-hek commented on lib/membrane_ice_plugin/handshake/handshake.ex
> +              | {:error, value :: integer()}
What about just raising in the handshake module, instead of returning error?

2021-03-18 13:46 UTC, mickel8 commented
I have also updated ex_libnice to 0.3.0

2021-03-18 14:26 UTC, mat-hek approved these changes

2021-03-18 14:27 UTC, merged