Non concurrent ice restart
membraneframework/membrane_ice_plugin pull request #29
Opened 2021-08-31 08:09 UTC by Rados13

Added sending notification when ice failed and when ice is ready and dtls handshake finished. Added also support for retransmit message from ExDTLS

2021-09-03 09:40 UTC, mat-hek requested changes

2021-09-03 09:40 UTC, mat-hek commented on lib/membrane_ice_plugin/connector.ex
> +        %State{parent: parent} = state
Let's move that match to the function body, or use the `state.parent` syntax. We rather avoid matching in function header if not necessary

2021-09-03 09:40 UTC, mat-hek commented on lib/membrane_ice_plugin/connector.ex
> +    # TODO: Change hardcoded 1 to component_id dependent on from who :retransmit come from
afaiu this is quite serious, as it can lead to weird bugs when having more than one component. Let's fix that if it's not too hard, or at least create an issue

2021-09-03 09:40 UTC, mat-hek commented on lib/membrane_ice_plugin/ice_bin.ex
> +    {{:ok, spec: spec, log_metadata: options.log_metadata}, %{:connector => connector}}
When you return `log_metadata` in a parent, it also affects all the children. Wouldn't that be sufficient?

2021-09-03 09:40 UTC, mat-hek commented on lib/membrane_ice_plugin/sink.ex
> +  )
seems like a formatter malfunction, braces shouldn't be there

2021-09-03 09:40 UTC, mat-hek commented on lib/membrane_ice_plugin/sink.ex
> +       again_ready?: false
actually we can use `key: :value` syntax for this whole map

2021-09-03 09:40 UTC, mat-hek commented on lib/membrane_ice_plugin/sink.ex
> +          [notify: :ice_ready]
```suggestion
        [demand: pad, event: {pad, %Handshake.Event{handshake_data: hsk_data}}, notify: :ice_ready]
```

2021-09-03 09:40 UTC, mat-hek commented on lib/membrane_ice_plugin/sink.ex
> +      end
Let's refactor this as we discussed. Make sure it works for many components

2021-09-03 16:47 UTC, mickel8 requested changes

2021-09-14 13:14 UTC, mat-hek requested changes

2021-09-14 13:14 UTC, mat-hek commented on lib/membrane_ice_plugin/ice_bin.ex
> +      {:error, _cause} = msg -> {{:ok, notify: msg}, state}
shouldn't we just send the `:connection_failed` notification? The error can be just logged using `debug`

2021-09-14 13:14 UTC, mat-hek commented on lib/membrane_ice_plugin/ice_bin.ex
> +    do: {{:ok, notify: :connection_failed}, state}
I think we should attach stream_id and component_id to the message. When there are multiple components, some may fail and some may succeed

2021-09-14 13:14 UTC, mat-hek commented on lib/membrane_ice_plugin/ice_bin.ex
> +      do: {{:ok, notify: :connection_ready}, state}
- Can't we get this information from the connector as well?
- Let's attach stream_id and component_id like for failures

2021-09-15 05:51 UTC, Rados13 commented on lib/membrane_ice_plugin/ice_bin.ex
> +      {:error, _cause} = msg -> {{:ok, notify: msg}, state}
I think we should't use :connection_failed, because for connection fail the standard handle would be run ice_restart, but I am not sure if we should run ice_restart when previous restart fail.

2021-09-15 11:36 UTC, mat-hek approved these changes

2021-09-15 11:46 UTC, merged