Cnode impl
membraneframework/membrane_ice_plugin pull request #3
Opened 2020-07-29 16:15 UTC by mickel8

2020-08-13 15:04 UTC, mat-hek commented on lib/membrane_ice/common.ex
> +    quote location: :keep do
Avoid generating such large blocks of code, because
- when the code is within `quote`, some warnings are not emitted
- you cannot split the code into private functions if you don't want them to be visible in the `use`ing module
- it makes the code harder to reason about

In this case
- handle_init is so small that it can be duplicated
- instead of injecting `handle_other`, the common module can have something like `handle_ice_message` and elements can do `def handle_other(...) do Common.handle_ice_message(...) ...`. No macro would even be needed that way

2020-08-13 15:28 UTC, mat-hek commented on lib/membrane_ice/sink.ex
> +    if !stream_id || !component_id do
Let's add an option like `get_stream_and_component` that would be a lambda accepting buffer and returning stream_id and component_id. That will be more flexible than requiring them to be in the metadata

2020-08-13 15:29 UTC, mat-hek commented on lib/membrane_ice/source.ex
> +defmodule Membrane.Element.ICE.Source do
```suggestion
defmodule Membrane.ICE.Source do
```

2020-08-13 15:37 UTC, mat-hek commented on examples/example_project/lib/sender.ex
> +    IO.inspect(msg, label: "pipeline")
let's use Logger.debug

2020-08-20 14:54 UTC, mickel8 commented on lib/membrane_ice/sink.ex
> +    if !stream_id || !component_id do
Hmm, I think we should do this using dynamic pads. Each pad would be identified by tuple `{stream_id, component_id}`. Sending `Buffer` on such pad would indicate where we want to send data. Pad would be created after receiving `NICE_COMPONENT_STATE_READY` message i.e. when connectivity checks end and connection establishes.

2020-09-01 11:05 UTC, mat-hek requested changes

2020-09-04 13:52 UTC, mickel8 commented
Summary: 

> minimize function invocations i.e. if something can be invoked by element like gathering candidates after getting local credentials do 

I think that the only thing we can do is to start gathering candidates after adding stream. This is not too big profit when we have to invoke manually bunch of other functions so I think it is better not to change it.

> return local candidates together (optimization)

By local I meant local `host`. It seems that `libnice` doesn't expose specific function for this. The only way to do this is to manually check which received candidates are host, accumulate them and return together. Not done in this PR made issue for this

TURN servers are not handled properly at this moment. Made issue for this #4

2020-09-07 13:30 UTC, mat-hek requested changes

2020-09-08 06:48 UTC, mat-hek approved these changes

2020-09-08 08:47 UTC, merged