Fixed buffer processing time metric
membraneframework/membrane_ice_plugin pull request #31
Opened 2023-03-08 12:39 UTC by shuntrho

2023-03-08 14:35 UTC, daniel-jodlos approved these changes

2023-03-08 15:17 UTC, FelonEkonom requested changes

2023-03-08 15:17 UTC, FelonEkonom commented on lib/membrane_ice_plugin/ice_endpoint.ex
> +      TelemetryMetrics.execute(@buffer_processing_time, %{}, %{}, telemetry_label)
This event is already emitted in line 829

```suggestion
```

2023-03-08 15:17 UTC, FelonEkonom commented on lib/membrane_ice_plugin/metrics.ex
> +        "ice.buffers_processed_time",
Maybe `"ice.buffers_processing_time"`?

2023-03-08 15:46 UTC, shuntrho commented on lib/membrane_ice_plugin/metrics.ex
> +        "ice.buffers_processed_time",
I wanted to indicate that this is a cumulative time of the buffers processed so far. But this new name fits as well.

2023-03-09 10:30 UTC, FelonEkonom approved these changes

2023-03-09 10:32 UTC, merged