Start and stop integrated TURN servers inside ICE Plugin
membraneframework/membrane_ice_plugin pull request #33
Opened 2021-11-10 11:01 UTC by FelonEkonom

2021-11-15 10:45 UTC, mickel8 requested changes

2021-11-15 10:45 UTC, mickel8 commented on lib/membrane_ice_plugin/ice_bin.ex
> +        else: []
I would move this code to `connector.ex` . As we discussed we can also get rid of `peer_pid` message.

2021-11-15 10:45 UTC, mickel8 commented on lib/membrane_ice_plugin/ice_bin.ex
> +                description: "Address, where integrated TURN server will be set up"
`Address integrated TURN server will listen at`

2021-11-15 14:39 UTC, FelonEkonom commented on lib/membrane_ice_plugin/ice_bin.ex
> +        else: []
Starting integrated TURN servers in `connector.ex` would make us have to send an extra message to `ICE.Bin` containing value holded in `integrated_turn_servers` variable, so I think that starting these TURN servers here is better solution

2021-11-17 11:23 UTC, mickel8 approved these changes

2021-11-17 11:23 UTC, mickel8 commented on mix.exs
> +      {:stun, github: "membraneframework/stun", branch: "removing-libnice"}
Remember to use master before merging

2021-11-17 15:41 UTC, merged